"""initial migration

Revision ID: 291c48e60620
Revises: 
Create Date: 2026-03-17 03:43:02.826899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291c48e60620'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('idem_key', sa.String(), nullable=False),
    sa.Column('req_id', sa.String(), nullable=False),
    sa.Column('req_status', sa.String(), nullable=False),
    sa.Column('req_hash', sa.String(), nullable=False),
    sa.Column('req_response', sa.Text(), nullable=True),
    sa.Column('req_code', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idem_key')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('ledger',
    sa.Column('ledger_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('ledger_id'),
    sa.UniqueConstraint('order_id', name='unique_order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger')
    op.drop_table('orders')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
